Magnite5/phoenixsupport
sonic-howl/frc2024 pull request #30
Opened 2024-01-24 00:06 UTC by magnite5

### 🛠 Proposed Changes:

[Briefly Describe the changes introduced by this pull request]

### 📝 Details:

- [Detail 1]

### 🔗 Related Issue(s):

- Resolves #[Issue Number]

2024-01-24 00:41 UTC, NathanGrenier requested changes

2024-01-24 00:41 UTC, NathanGrenier commented on constants/RobotConstants.py
> +  isSimulation = False
There's a function to determine this. `wpilib.RobotBase.isReal()`

2024-01-24 00:41 UTC, NathanGrenier commented on swerve/SwerveModule.py
> +    self.swerve_dashboard = network_table_instance.getTable(
Not sure if we'd do this over the network table.

If you use the shuffleboard, the data will be published to the network table and visually to the shuffleboard.

2024-01-24 00:41 UTC, NathanGrenier commented on swerve/SwerveSubsystems.py
> +    if not RobotConstants.isSimulation:
Replace this with the proper way of determining if the code is running in a simulation (described above in another comment).

2024-01-24 00:41 UTC, NathanGrenier commented on swerve/SwerveSubsystems.py
> +    if RobotConstants.isSimulation:
Replace this with the proper way of determining if the code is running in a simulation (described above in another comment).

2024-01-24 00:42 UTC, NathanGrenier commented on .pre-commit-config.yaml
Keep this. It's just a config file to install the pre-commit hook. 

If you don't want any pre-commit functionality, don't install it via the `pre-commit` command. If it's already installed, delete the hook from the hidden `.git` folder.

2024-01-24 00:44 UTC, NathanGrenier commented
Shouldn't this branch be merged into the `develop` branch?

2024-01-24 01:30 UTC, Portnord requested changes
Is this a mentor branch? Who's Magnite5?

2024-01-24 01:45 UTC, NathanGrenier commented
Is this a mentor branch? Who's Magnite5?

2024-01-25 17:39 UTC, Portnord commented
Closing this request. Work has been transferred to and continues on feature/drivebase.

2024-01-25 17:39 UTC, closed without merging